spring:
  application:
    name: zuul

server:
  port: 8080

zuul:
  routes:
    productcatalogue:
      path: /productcatalogue/**
      url: http://productcatalogue:8080/
    stockmanager:
      path: /stockmanager/**
      url: http://stockmanager:8080/