language: java
jdk: oraclejdk8
sudo: required

services:
  - docker

env:
  global:
  # DOCKER_USER + DOCKER_PASS
  - secure: "vcvnrY/s24onu6ck2HBHvB0arn1Pu0vFZ9qzWc8cJs3ogkCLEKeLKTp2E0t2kFghzLzLlZ3BEDlslm96u+jezuAq83pIEAYmVJz89PwpSuHs/sh6Tki1tUrfMm9yBGnGP84MDS/yvRR3I919TkQ+2wKOOG5ROunJbMI2/7oksKhtjFui6csmPdiRXgof2RAmwTU+xtVPUi5Rhnp+Re4apmFbXj7MutT5Qu7C6UHs0kDe6CPzriVw2E1opCNVx/1NAFY0RUu8+QmubqbxPBJq4xkibclmb1qn/FuNblI2ee8jHHalZ89U+w6O9eexoSZX+CGHzeCKYUsIUj6Et6WlPUoGQYNkoxYlmClnZNg8UW/sHyP1MxGYulhjsYZbdLF5wVUf6Tkt+2Hji/MagkypMT9lpORGDvy5X3nZMAr8cGEVvtrITC6nH3sAPdGZbuIe3P/0ckd49761vNv5BzER436U5fCSqebCpGsdoQff/rA2lQ4rhr+kw0CjMbwO69oGqYT/2EUEFjxnZqKC7KTQLphsXAZPHiC/CZnDgJi12NWU/tydHYUTGnY9SfdXeShjWcrN56WCZ/QfbUWSlPs47RjRM+SUFS6xVFxtgL2UjUQbGkGfLuBGDZwtDihGcERbR0gKTYrQavpHt47975xFpNzVDzxg/uybMIWjch8tJkQ="
  - secure: "kVGiff1QmHJIUOYZIgRtuwzgTy50A97L7s+OK3DNCvP5MXl6xSiUDzVqb27J+zkqrckfIAznAyfdzlCZPaQbNGRymvQfzUqOBFRW8MZ9wK8JfXKks9j38uLG9YIjSqYhqnd9oGnRW92Ix8go/yiegsYpaTp7DWW5+j306zq1jR0was807/RaDamzl69Ex7HlxPUKhQ5TwIKgELSKfwDSt5e4c/I8asF9EAcvfcdv81IuyrZxy+Ni9yVrdvgkt1TBlpXi6gYmJpHGlZo1aHFRdwYjfKPAWVXoQAbPGiYI6pUoDI5skh5YDnDvnr8iqTPIAJAUXKrD5zy8sEKWgIWgu5WswNBrUAiWEWfWzfRc7jT6VofhHeM5OCWNwSFItoE6S6K1L7sS7MyczEFlOmT9aTbSMKnzjF31++y3kAaA5RgbxTgK5GNITV4m6RvnC36vn6FgmxDrgqEONSjslypgshpJeYKXzU6mI8F3A90hc4FsvzPP4cEntVqeWryDxqZT3PXVXMLN/jjUmUqq4xC1oegdgcNVWWsjZu6rmGQGyjRBoMWrVmZ8UOGjtpenvNn418JldARpkYAIYsCzGr1fIXr8gSbj8Vaah0Zvj8hBA+JWOj7JPS8FUqJ1bhlglCXaWuKmlVsiJI6jqGPlXyoVNo5YN8Xlj3VhZbfC/L/SGqo="
  - COMMIT=${TRAVIS_COMMIT::7}

script:
- ./mvnw clean install -B

cache:
  directories:
    - '$HOME/.m2/repository'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=cbonami/stockmanager
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME