language: java
jdk: oraclejdk8
sudo: required

services:
  - docker

env:
  global:
  # DOCKER_USER + DOCKER_PASS
  - secure: "rHJM/eUJPR61HFNWUlRU1gQxFhNwxMfB7RN5SaAD4//7rTq9GsUfmwqyBG3qSOiEsgph1hYXmFATBDqYNpzRuN+k2Yp/kqwJcDjuqzhSx2S0jilPFR3BtkbvTi1esi+FsTGm6cXCB6TGIa/2Jc0MojDnaacbLgmGWaaZfg38cA8sG+Dpq/ZudWEZeFqX5ag7ULVw3c6aykNQO5Wd+tVtj8c/dA7BIYCLLLB12OgM0tFvbib+uNi+Kl3wJ90Vqx++ssNUJR0Esg3s4xHfjNmz1l/+c1Kw70shulGuaRl7ePyadRcoPhq241o2lcX8mLPRwFQGtkGCmDuNOtJwAmZj5JnjUmk9/Qnb2hTGjKi409aY3wG8x8cFawLKqF8WHRr0JW4plusShk3x3w0SqprZVFdckihjhblx3bLLjSGHY9EBDdx3wQk9DNFoZFYzgsEn5sTstXRDJcv0r2IYFAqor0wRiYJfNvYuy0s1tcAkvZbJUvjepvyDkSuS1rz9ttYXkzy6WTdYxIjiHguCMrq5tw7xPtJI3IouF4uypFR8XcBsIrm0bcsl/YR5n62M7NlUUy03BeY5GkKU04oFS1U/yiUQegwjy9U2Iy4b/TtKi8wmN0W8DujeOgw+8BwUeHNuo8j1+RUtnCFa8LQJ3AE3KUsZM/8NZr8ST02xBrgfDZM="
  - secure: "EcjSzb1Irm21b6aKgazfK8cIHD5mYQ5HXtnQWeHB2RfIxXyCeSwY2R3XJRYd2smbkktQVBv2ETpR32LmiIFBrHKJJ5p8Bl7g/e9yfW5S18ybcswCcH5i0PxXSNz7B9bnHFmvwRUocrcGDiJnSJkFE9dRdvPeUT9zWdJclX4zCT7bI73qi4Tlv23vWDxzW2tsQ30hEjUviFIGaiEmJxwFpGALV2Qh5xrZaUhqNrV8DsvXvzA4h4CQX4wBTjpUerIdTipsNH+OLjsIh7a/WLs8csHJOvnC78UX4ySHjNJdII1P5R+1/rUhX63kr6brGxcAwmoRHJHpDF5QFQ2Dfbv3juy0VrVRE6sFMU1TF7cgQcwhVNi0iXsoOZ9Q0NPc30Hax3smYWJ2RsgZj8uHER2giZypb3ztqX3Y7KqgUmcZK0WNaj/2t3Y9cpaJh9FEYsehfRdKdes52DV4TIgL/xwEzWx2gh7vKAOeKyzIiJFgmVWfi9ywfOPtVgfmqivfRGAQwpB8vRWIv6uHumi+iaHn1220IW3bHRvRKu3FqHOQWIo8ycnHEHKHvmQ2u6IVi67En+fJfjD+I6zD+1gcpp4DBj2nenebBARqzuu8+WJO+mBZJkbmAv05iiMG6ndb2KGBAVTBG7wSmjdZr/a/Kpz0LKWDJ+bD66YHG04A0igR56k="
  - COMMIT=${TRAVIS_COMMIT::7}

script:
- ./mvnw clean install -B

cache:
  directories:
    - '$HOME/.m2/repository'

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=cbonami/productcatalogue
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME